"""Add frozen_balance to Balance and update Order model

Revision ID: 716da266892a
Revises: c8ef10802744
Create Date: 2025-11-08 16:33:57.138762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716da266892a'
down_revision: Union[str, Sequence[str], None] = 'c8ef10802744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add frozen_balance to balances with default value 0
    op.add_column('balances', sa.Column('frozen_balance', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))

    # Add frozen_amount to orders with default value 0
    op.add_column('orders', sa.Column('frozen_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))

    # Update existing orders: set frozen_amount = total_amount for pending orders
    op.execute("UPDATE orders SET frozen_amount = total_amount WHERE status = 'pending'")

    # Create indexes
    op.create_index(op.f('ix_orders_equipment_id'), 'orders', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_equipment_id'), table_name='orders')
    op.drop_column('orders', 'frozen_amount')
    op.drop_column('balances', 'frozen_balance')
    # ### end Alembic commands ###
