"""Add order_id to balance_transactions and update transaction types

Revision ID: d29c11dfba6d
Revises: 7391b998496f
Create Date: 2025-11-16 21:31:34.194145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29c11dfba6d'
down_revision: Union[str, Sequence[str], None] = '7391b998496f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_transactions', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'balance_transactions', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance_transactions', type_='foreignkey')
    op.drop_column('balance_transactions', 'order_id')
    # ### end Alembic commands ###
