"""Add delivery_distance and delivery_fee to orders

Revision ID: 7391b998496f
Revises: 23ce06b963a3
Create Date: 2025-11-16 15:36:33.767312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7391b998496f'
down_revision: Union[str, Sequence[str], None] = '23ce06b963a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_distance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_fee')
    op.drop_column('orders', 'delivery_distance')
    # ### end Alembic commands ###
