"""Add delivery_price_per_km to equipment

Revision ID: 23ce06b963a3
Revises: 1d165ed0c603
Create Date: 2025-11-16 13:07:39.382437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ce06b963a3'
down_revision: Union[str, Sequence[str], None] = '1d165ed0c603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('delivery_price_per_km', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'delivery_price_per_km')
    # ### end Alembic commands ###
