"""Add delivery location to orders

Revision ID: 1d165ed0c603
Revises: 3e9dabf257b8
Create Date: 2025-11-16 12:54:05.913393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d165ed0c603'
down_revision: Union[str, Sequence[str], None] = '3e9dabf257b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Avval nullable qilib qo'shamiz
    op.add_column('orders', sa.Column('delivery_latitude', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('delivery_longitude', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))

    # Mavjud orderlar uchun default qiymat beramiz (0,0 - noma'lum joylashuv)
    op.execute("UPDATE orders SET delivery_latitude = '0' WHERE delivery_latitude IS NULL")
    op.execute("UPDATE orders SET delivery_longitude = '0' WHERE delivery_longitude IS NULL")

    # Endi NOT NULL constraint qo'shamiz
    op.alter_column('orders', 'delivery_latitude', nullable=False)
    op.alter_column('orders', 'delivery_longitude', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'delivery_longitude')
    op.drop_column('orders', 'delivery_latitude')
    # ### end Alembic commands ###
