"""Add OTP and Eskiz token tables

Revision ID: d6cae9b10641
Revises: 
Create Date: 2025-11-08 12:17:51.520719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6cae9b10641'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_equipment_lat_lng'), table_name='equipment')
    op.drop_index(op.f('idx_equipment_owner'), table_name='equipment')
    op.drop_index(op.f('idx_equipment_status'), table_name='equipment')
    op.drop_index(op.f('idx_equipment_type'), table_name='equipment')
    op.drop_index(op.f('idx_messages_chat'), table_name='messages')
    op.drop_index(op.f('idx_messages_sender'), table_name='messages')
    op.drop_index(op.f('idx_orders_equipment'), table_name='orders')
    op.drop_index(op.f('idx_orders_status'), table_name='orders')
    op.drop_index(op.f('idx_orders_user'), table_name='orders')
    op.drop_index(op.f('idx_payments_order'), table_name='payments')
    op.drop_index(op.f('idx_payments_status'), table_name='payments')
    op.drop_index(op.f('idx_reviews_equipment'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_user'), table_name='reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_reviews_user'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('idx_reviews_equipment'), 'reviews', ['equipment_id'], unique=False)
    op.create_index(op.f('idx_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('idx_payments_order'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('idx_orders_user'), 'orders', ['user_id'], unique=False)
    op.create_index(op.f('idx_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('idx_orders_equipment'), 'orders', ['equipment_id'], unique=False)
    op.create_index(op.f('idx_messages_sender'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_messages_chat'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('idx_equipment_type'), 'equipment', ['type'], unique=False)
    op.create_index(op.f('idx_equipment_status'), 'equipment', ['status'], unique=False)
    op.create_index(op.f('idx_equipment_owner'), 'equipment', ['owner_id'], unique=False)
    op.create_index(op.f('idx_equipment_lat_lng'), 'equipment', ['latitude', 'longitude'], unique=False)
    # ### end Alembic commands ###
